#! /bin/bash
# a tiny code statistical tool
# use for small projects only

exts=( rb py c cc h js )
summary=0
declare -a ignore
declare -A file_hash

while getopts "i:hs" opt
do
    case $opt in
        i)
            ignore+=($OPTARG);;
        s)
            summary=1;;
	h)
	    cat <<EOF

Usage:
 lines
 lines -h
 lines [-i ignore_pattern]

Options:
 -h     print this help
 -i     ignore pattern
EOF
	    exit;;
    esac
done

function match_in() {
    local elem="$1"
    shift
    local striped
    for pattern in "$@"
    do
        striped=${elem/$pattern/}
        # matched
        [[ $elem != $striped ]] && return 0
    done
    return 1
}

filelist=$(find . -type f)
for f in $filelist
do
    match_in $f ${ignore[@]} && continue
    # fname=$(basename $f)
    fname=${f##*/}
    # filter hidden or swap file
    if [[ $fname != *~ && $fname != \.* ]]
    then
        # get file extension
        fext=${fname##*.}
        for ext in ${exts[@]}
        do
            if [ "$ext" = "$fext" ]
            then
                file_hash["$ext"]+="$f\0"
            fi
        done
    fi
done

if [ $summary -eq 1 ]
then
    echo ext files lines
    echo "------------"
    for key in "${!file_hash[@]}"
    do
        echo -n "$key "
        echo -e -n ${file_hash[$key]} | wc -l --files0-from=- | nl | tail -1 | awk '{print $1-1, $2}'
        echo "------------"
    done
else
    for key in "${!file_hash[@]}"
    do
        # echo $key
        # echo ${file_hash[$key]}
        echo -e -n ${file_hash[$key]} | wc -l --files0-from=- | sort -n
        echo "------------"
    done
fi
